language: node_js
node_js:
  - "12"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "4.2"
env:
  - HUBOT_VERSION=">=2.0 <3" COFFEESCRIPT_VERSION=">=1.6.3 <2.0"
  - HUBOT_VERSION="^3.0" COFFEESCRIPT_VERSION=">=1.6.3 <2.0"
  - HUBOT_VERSION="^3.0" COFFEESCRIPT_VERSION="^2.0"
# Excluding tests with Coffeescript 2 on nodejs version <= 5
# because the syntax incompatible issue. Coffeescript 2 use
# destructuring assignment syntax at https://git.io/fjcq2 but
# nodejs <= 5 doesn't support.
matrix:
  exclude:
    - node_js: "4.2"
      env: HUBOT_VERSION="^3.0" COFFEESCRIPT_VERSION="^2.0"
    - node_js: "4"
      env: HUBOT_VERSION="^3.0" COFFEESCRIPT_VERSION="^2.0"
    - node_js: "5"
      env: HUBOT_VERSION="^3.0" COFFEESCRIPT_VERSION="^2.0"
after_success:
  - npm run codecov
# The second step here installs the specific hubot version determined
# by the `env` specified in the matrix. That lets us test against
# multiple Hubot versions. This is a bit messy, but works around
# package.json only being able to specify one version.
script: npm install && npm install hubot@"$HUBOT_VERSION" coffeescript@"$COFFEESCRIPT_VERSION" && npm test
